// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CloseTerminal(arg1:string):Promise<void>;

export function GetRepoGroups():Promise<Array<model.RepoGroup>>;

export function GetSessionMessages(arg1:string):Promise<Array<model.Message>>;

export function LaunchNewChat(arg1:string):Promise<string>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResumeSession(arg1:string):Promise<string>;

export function Search(arg1:string):Promise<Array<model.Session>>;

export function ToggleFavorite(arg1:string):Promise<void>;

export function WriteToTerminal(arg1:string,arg2:string):Promise<void>;
